license="MIT"

[[mods]]
    issueTrackerURL="https://github.com/BlakeBr0/MoreBuckets/issues"
    modId="morebuckets"
    version="${mod_version}"
    displayName="More Buckets"
    updateJSONURL="https://api.blakesmods.com/v2/mods/morebuckets/26.1/updates"
    displayURL="https://blakesmods.com/more-buckets"
    # logoFile="examplemod.png"
    authors="BlakeBr0"
    credits="thorgot"
    description='''
    Adds a bunch of new buckets.
    '''

    [[dependencies.morebuckets]]
        modId="neoforge"
        mandatory=true
        versionRange="[26.1.0.0-beta,)"
        ordering="NONE"
        side="BOTH"
    [[dependencies.morebuckets]]
        modId="minecraft"
        mandatory=true
        versionRange="[26.1)"
        ordering="NONE"
        side="BOTH"
    [[dependencies.morebuckets]]
        modId="cucumber"
        mandatory=true
        versionRange="[${cucumber_version},)"
        ordering="NONE"
        side="BOTH"